export interface TenantContact {
  name: string;
  title?: string;
  email?: string;
  phone?: string;
}

export interface TenantCase {
  caseNumber: string;
  subject: string;
  status: string;
  dato: string; // "YYYY-MM-DD"
  sfUrl: string | null;
}

export interface Tenant {
  id: string;
  kontonavn: string;
  kundenummer?: string;
  orgnummer?: string;
  bygg?: string;
  kontoeier?: string;
  adresse?: string;
  kontakter: TenantContact[];
  sisteSaker: TenantCase[];
  sfUrl: string | null;
}

/**
 * MIDLERTIDIG ANONYMISERT — se merknad i widgets.anon.ts for konvensjonen. Kontonavn byttet til
 * "Demokunde N" (gjenbruker eksisterende nummerering fra widgets.anon.ts der samme leietaker
 * allerede opptrer — "First Rent A Car Norway AS" = Demokunde 6 — ellers fortløpende fra 30).
 * Org.nummer og fakturaadresse er FJERNET her (ikke bare byttet) siden org.nummer alene er nok til
 * å slå opp reell identitet i Brønnøysundregistrene. Kontaktpersoner (reelle privatpersoner hos
 * leietaker) er anonymisert til "Kontaktperson N" med rolle beholdt, e-post/telefon fjernet.
 * Saksemner er generiske siden fritekst kan inneholde identifiserende detaljer — saksnummer/status/
 * dato/kobling til bygg beholdt. sfUrl er null (peker uansett til en reell SF-konto/-sak).
 */
export const TENANTS: Tenant[] = [
  { id: "t1", kontonavn: "Demokunde 30", kundenummer: "10821", orgnummer: undefined, bygg: "Vollsveien 13 C", kontoeier: "Ingeborg Tveit", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "COO" }, { name: "Kontaktperson 2", title: "Driftsansvarlig" }, { name: "Kontaktperson 3", title: "Økonomiansvarlig" }, { name: "Kontaktperson 4" }, { name: "Kontaktperson 5" }], sisteSaker: [{ caseNumber: "00113177", subject: "(sak - detaljer i lokal versjon)", status: "Iverksettes", dato: "2026-08-10", sfUrl: null }, { caseNumber: "00112988", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-05", sfUrl: null }, { caseNumber: "00109547", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-08", sfUrl: null }], sfUrl: null },
  { id: "t2", kontonavn: "Demokunde 31", kundenummer: "11020", orgnummer: undefined, bygg: "Vollsveien 13 H", kontoeier: "Ingeborg Tveit", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }, { name: "Kontaktperson 2", title: "Logistikksjef" }, { name: "Kontaktperson 3", title: "Managing Director" }, { name: "Kontaktperson 4" }, { name: "Kontaktperson 5" }], sisteSaker: [{ caseNumber: "00105400", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-03-16", sfUrl: null }, { caseNumber: "00104201", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-02-20", sfUrl: null }, { caseNumber: "00103944", subject: "(sak - detaljer i lokal versjon)", status: "Flettet", dato: "2026-02-13", sfUrl: null }], sfUrl: null },
  { id: "t3", kontonavn: "Demokunde 32", kundenummer: "1002050", orgnummer: undefined, bygg: undefined, kontoeier: "Christian Geelmuyden", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }], sisteSaker: [{ caseNumber: "00113315", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-12", sfUrl: null }], sfUrl: null },
  { id: "t4", kontonavn: "Demokunde 6", kundenummer: "10812", orgnummer: undefined, bygg: "Lilleakerveien 2 C", kontoeier: "Elin Cappelen", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }, { name: "Kontaktperson 2" }, { name: "Kontaktperson 3", title: "Adminstrerende direktør" }, { name: "Kontaktperson 4", title: "Chief marketing & communications officer" }, { name: "Kontaktperson 5", title: "Senior Advisor IT" }], sisteSaker: [{ caseNumber: "00113285", subject: "(sak - detaljer i lokal versjon)", status: "Iverksettes", dato: "2026-08-11", sfUrl: null }, { caseNumber: "00112996", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-06", sfUrl: null }, { caseNumber: "00112458", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-27", sfUrl: null }], sfUrl: null },
  { id: "t5", kontonavn: "Demokunde 33", kundenummer: "11023", orgnummer: undefined, bygg: "Lilleakerveien 31 (29)", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }, { name: "Kontaktperson 2", title: "Daglig leder" }, { name: "Kontaktperson 3", title: "Styreleder" }, { name: "Kontaktperson 4" }], sisteSaker: [{ caseNumber: "00108283", subject: "(sak - detaljer i lokal versjon)", status: "Closed", dato: "2026-05-19", sfUrl: null }, { caseNumber: "00107081", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-04-23", sfUrl: null }, { caseNumber: "00106467", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-04-10", sfUrl: null }], sfUrl: null },
  { id: "t6", kontonavn: "Demokunde 34", kundenummer: "10781", orgnummer: undefined, bygg: "Mustads Vei 1", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Teamleder BPA" }, { name: "Kontaktperson 2" }, { name: "Kontaktperson 3", title: "HR-administrator" }, { name: "Kontaktperson 4" }, { name: "Kontaktperson 5" }], sisteSaker: [{ caseNumber: "00113258", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-11", sfUrl: null }, { caseNumber: "00113226", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-11", sfUrl: null }, { caseNumber: "00113180", subject: "(sak - detaljer i lokal versjon)", status: "Flettet", dato: "2026-08-10", sfUrl: null }], sfUrl: null },
  { id: "t7", kontonavn: "Demokunde 35", kundenummer: "31131", orgnummer: undefined, bygg: "Lilleakerveien 22 VW", kontoeier: "Christian Geelmuyden", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Sentralbord" }, { name: "Kontaktperson 2", title: "Drift & kvalitetsansvarlig/ brannvernansvarlig" }, { name: "Kontaktperson 3", title: "Markedssjef Volkswagen nyttekjøretøy" }, { name: "Kontaktperson 4" }], sisteSaker: [{ caseNumber: "00113229", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-11", sfUrl: null }, { caseNumber: "00112354", subject: "(sak - detaljer i lokal versjon)", status: "Iverksettes", dato: "2026-07-23", sfUrl: null }, { caseNumber: "00112226", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-20", sfUrl: null }], sfUrl: null },
  { id: "t8", kontonavn: "Demokunde 36", kundenummer: "1002048", orgnummer: undefined, bygg: "Lilleakerveien 4 D - Trekantbygget", kontoeier: "Camilla Bang Hoff", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }], sisteSaker: [{ caseNumber: "00113195", subject: "(sak - detaljer i lokal versjon)", status: "Escalated", dato: "2026-08-10", sfUrl: null }, { caseNumber: "00113058", subject: "(sak - detaljer i lokal versjon)", status: "Ny", dato: "2026-08-06", sfUrl: null }, { caseNumber: "00112930", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-05", sfUrl: null }], sfUrl: null },
  { id: "t9", kontonavn: "Demokunde 37", kundenummer: "11022", orgnummer: undefined, bygg: "Lilleakerveien 31 (29)", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }, { name: "Kontaktperson 2" }, { name: "Kontaktperson 3" }, { name: "Kontaktperson 4" }, { name: "Kontaktperson 5", title: "Butikkleder" }], sisteSaker: [{ caseNumber: "00112584", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-29", sfUrl: null }, { caseNumber: "00108444", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-05-20", sfUrl: null }, { caseNumber: "00106316", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-04-08", sfUrl: null }], sfUrl: null },
  { id: "t10", kontonavn: "Demokunde 38", kundenummer: "31342", orgnummer: undefined, bygg: "Mustads Vei 12", kontoeier: "Elin Cappelen", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }, { name: "Kontaktperson 2" }], sisteSaker: [{ caseNumber: "00113015", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-06", sfUrl: null }, { caseNumber: "00112914", subject: "(sak - detaljer i lokal versjon)", status: "Avventer_Kunde", dato: "2026-08-05", sfUrl: null }, { caseNumber: "00112439", subject: "(sak - detaljer i lokal versjon)", status: "Avventer_Kunde", dato: "2026-07-26", sfUrl: null }], sfUrl: null },
  { id: "t11", kontonavn: "Demokunde 39", kundenummer: "11091", orgnummer: undefined, bygg: "Lilleakerveien 31 (29)", kontoeier: "Tone Engnes", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }, { name: "Kontaktperson 2" }, { name: "Kontaktperson 3", title: "Butikkleder" }, { name: "Kontaktperson 4" }], sisteSaker: [{ caseNumber: "00109075", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-01", sfUrl: null }, { caseNumber: "00109074", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-01", sfUrl: null }, { caseNumber: "00108720", subject: "(sak - detaljer i lokal versjon)", status: "Flettet", dato: "2026-05-26", sfUrl: null }], sfUrl: null },
  { id: "t12", kontonavn: "Demokunde 40", kundenummer: "11086", orgnummer: undefined, bygg: "CC Vest - Lilleakerveien 16", kontoeier: "Elin Cappelen", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }], sisteSaker: [{ caseNumber: "00109754", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-11", sfUrl: null }, { caseNumber: "00108450", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-05-20", sfUrl: null }, { caseNumber: "00104731", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-03-03", sfUrl: null }], sfUrl: null },
  { id: "t13", kontonavn: "Demokunde 41", kundenummer: "11047", orgnummer: undefined, bygg: "Lilleakerveien 4 C", kontoeier: "Camilla Bang Hoff", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Innkjøpssjef TV2" }, { name: "Kontaktperson 2", title: "Nyhetsredaktør" }, { name: "Kontaktperson 3", title: "Markedsansvarlig" }, { name: "Kontaktperson 4", title: "Koordinator TV2" }, { name: "Kontaktperson 5", title: "Bios - Arkitekt på prosjektet" }], sisteSaker: [{ caseNumber: "00113342", subject: "(sak - detaljer i lokal versjon)", status: "Avventer_Kunde", dato: "2026-08-12", sfUrl: null }, { caseNumber: "00110641", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-24", sfUrl: null }, { caseNumber: "00110275", subject: "(sak - detaljer i lokal versjon)", status: "Closed", dato: "2026-06-19", sfUrl: null }], sfUrl: null },
  { id: "t14", kontonavn: "Demokunde 42", kundenummer: "11064", orgnummer: undefined, bygg: "Lilleakerveien 4 D - Trekantbygget", kontoeier: "Camilla Bang Hoff", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Eier" }], sisteSaker: [{ caseNumber: "00110527", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-23", sfUrl: null }, { caseNumber: "00109950", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-15", sfUrl: null }, { caseNumber: "00109375", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-04", sfUrl: null }], sfUrl: null },
  { id: "t15", kontonavn: "Demokunde 43", kundenummer: "11021", orgnummer: undefined, bygg: "Lilleakerveien 31 (29)", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Distriktssjef" }, { name: "Kontaktperson 2", title: "Regnskap" }, { name: "Kontaktperson 3", title: "Drift" }, { name: "Kontaktperson 4", title: "Kontraktsanvarlig" }, { name: "Kontaktperson 5", title: "Tidligere butikksjef" }], sisteSaker: [{ caseNumber: "00111689", subject: "(sak - detaljer i lokal versjon)", status: "Ny", dato: "2026-07-08", sfUrl: null }, { caseNumber: "00108630", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-05-22", sfUrl: null }, { caseNumber: "00108598", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-05-22", sfUrl: null }], sfUrl: null },
  { id: "t16", kontonavn: "Demokunde 44", kundenummer: "11017", orgnummer: undefined, bygg: "Lilleakerveien 31 (29)", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Daglig leder/Eier" }, { name: "Kontaktperson 2" }, { name: "Kontaktperson 3" }], sisteSaker: [{ caseNumber: "00104060", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-02-17", sfUrl: null }, { caseNumber: "00100932", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2025-12-09", sfUrl: null }, { caseNumber: "00094222", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2025-08-13", sfUrl: null }], sfUrl: null },
  { id: "t17", kontonavn: "Demokunde 45", kundenummer: "11018", orgnummer: undefined, bygg: "Lilleakerveien 31 (29)", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Butikksjef/Eier" }, { name: "Kontaktperson 2", title: "Styremedlem/økonomi" }], sisteSaker: [{ caseNumber: "00110742", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-25", sfUrl: null }, { caseNumber: "00109733", subject: "(sak - detaljer i lokal versjon)", status: "Iverksettes", dato: "2026-06-10", sfUrl: null }, { caseNumber: "00105560", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-03-18", sfUrl: null }], sfUrl: null },
  { id: "t18", kontonavn: "Demokunde 46", kundenummer: "31052", orgnummer: undefined, bygg: "Lilleakerveien 31 (29)", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Eier" }, { name: "Kontaktperson 2", title: "Eier" }], sisteSaker: [{ caseNumber: "00110165", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-17", sfUrl: null }, { caseNumber: "00108111", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-05-14", sfUrl: null }, { caseNumber: "00107751", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-05-08", sfUrl: null }], sfUrl: null },
  { id: "t19", kontonavn: "Demokunde 47", kundenummer: "11019", orgnummer: undefined, bygg: "Lilleakerveien 31 (29)", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Butikksjef/eier" }], sisteSaker: [{ caseNumber: "00112773", subject: "(sak - detaljer i lokal versjon)", status: "Ny", dato: "2026-08-03", sfUrl: null }, { caseNumber: "00109570", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-08", sfUrl: null }, { caseNumber: "00109329", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-03", sfUrl: null }], sfUrl: null },
  { id: "t20", kontonavn: "Demokunde 48", kundenummer: "11013", orgnummer: undefined, bygg: "Lilleakerveien 31 (29)", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Butikksjef/Eier" }, { name: "Kontaktperson 2" }], sisteSaker: [{ caseNumber: "00113103", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-07", sfUrl: null }, { caseNumber: "00111968", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-14", sfUrl: null }, { caseNumber: "00111802", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-09", sfUrl: null }], sfUrl: null },
  { id: "t21", kontonavn: "Demokunde 49", kundenummer: "31332", orgnummer: undefined, bygg: "Vollsveien 13 D", kontoeier: "Ingeborg Tveit", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }], sisteSaker: [{ caseNumber: "00112258", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-21", sfUrl: null }, { caseNumber: "00111453", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-03", sfUrl: null }, { caseNumber: "00110838", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-25", sfUrl: null }], sfUrl: null },
  { id: "t22", kontonavn: "Demokunde 50", kundenummer: "1000095", orgnummer: undefined, bygg: "Vollsveien 13 D", kontoeier: "Ingeborg Tveit", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }], sisteSaker: [], sfUrl: null },
  { id: "t23", kontonavn: "Demokunde 51", kundenummer: "11127", orgnummer: undefined, bygg: "Vollsveien 13 D", kontoeier: "Ingeborg Tveit", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Ski Technician // Workshop Manager" }], sisteSaker: [{ caseNumber: "00113055", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-06", sfUrl: null }, { caseNumber: "00109949", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-15", sfUrl: null }, { caseNumber: "00109948", subject: "(sak - detaljer i lokal versjon)", status: "Ny", dato: "2026-06-15", sfUrl: null }], sfUrl: null },
  { id: "t24", kontonavn: "Demokunde 52", kundenummer: "10279", orgnummer: undefined, bygg: "Vollsveien 13 H", kontoeier: "Ingeborg Tveit", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Kontrakt" }, { name: "Kontaktperson 2", title: "Butikksjef" }, { name: "Kontaktperson 3" }, { name: "Kontaktperson 4", title: "Business Controller" }, { name: "Kontaktperson 5" }], sisteSaker: [{ caseNumber: "00113029", subject: "(sak - detaljer i lokal versjon)", status: "Avventer_Kunde", dato: "2026-08-06", sfUrl: null }, { caseNumber: "00111707", subject: "(sak - detaljer i lokal versjon)", status: "Closed", dato: "2026-07-08", sfUrl: null }, { caseNumber: "00109594", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-09", sfUrl: null }], sfUrl: null },
  { id: "t25", kontonavn: "Demokunde 53", kundenummer: "10773", orgnummer: undefined, bygg: "Mustads Vei 1", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }, { name: "Kontaktperson 2", title: "CFO" }, { name: "Kontaktperson 3", title: "Project and Organizational Lead" }, { name: "Kontaktperson 4" }, { name: "Kontaktperson 5", title: "Styremedlem" }], sisteSaker: [{ caseNumber: "00112787", subject: "(sak - detaljer i lokal versjon)", status: "Avventer_Kunde", dato: "2026-08-03", sfUrl: null }, { caseNumber: "00112473", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-27", sfUrl: null }, { caseNumber: "00112463", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-27", sfUrl: null }], sfUrl: null },
  { id: "t26", kontonavn: "Demokunde 54", kundenummer: "10358", orgnummer: undefined, bygg: "Mustads Vei 1", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Regional driftssjef" }, { name: "Kontaktperson 2" }, { name: "Kontaktperson 3", title: "Daglig leder/Kontraktansvarlig" }, { name: "Kontaktperson 4" }, { name: "Kontaktperson 5" }], sisteSaker: [{ caseNumber: "00112067", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-16", sfUrl: null }, { caseNumber: "00111615", subject: "(sak - detaljer i lokal versjon)", status: "Iverksettes", dato: "2026-07-07", sfUrl: null }, { caseNumber: "00111042", subject: "(sak - detaljer i lokal versjon)", status: "Closed", dato: "2026-06-29", sfUrl: null }], sfUrl: null },
  { id: "t27", kontonavn: "Demokunde 55", kundenummer: "10473", orgnummer: undefined, bygg: "Mustads Vei 1", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Administrerende direktør" }, { name: "Kontaktperson 2", title: "Kontorleder" }, { name: "Kontaktperson 3", title: "Virksomhetsstøtte" }, { name: "Kontaktperson 4" }, { name: "Kontaktperson 5", title: "Adm. dir" }], sisteSaker: [{ caseNumber: "00113322", subject: "(sak - detaljer i lokal versjon)", status: "Iverksettes", dato: "2026-08-12", sfUrl: null }, { caseNumber: "00112644", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-30", sfUrl: null }, { caseNumber: "00109810", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-11", sfUrl: null }], sfUrl: null },
  { id: "t28", kontonavn: "Demokunde 56", kundenummer: "10305", orgnummer: undefined, bygg: "Mustads Vei 1", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1" }, { name: "Kontaktperson 2" }, { name: "Kontaktperson 3", title: "Fagsjef / Sector Manager" }, { name: "Kontaktperson 4", title: "Finance manager" }, { name: "Kontaktperson 5", title: "Fagsjef" }], sisteSaker: [{ caseNumber: "00110631", subject: "(sak - detaljer i lokal versjon)", status: "Closed", dato: "2026-06-24", sfUrl: null }, { caseNumber: "00109824", subject: "(sak - detaljer i lokal versjon)", status: "Avventer_Kunde", dato: "2026-06-11", sfUrl: null }, { caseNumber: "00109356", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-06-04", sfUrl: null }], sfUrl: null },
  { id: "t29", kontonavn: "Demokunde 57", kundenummer: "10303", orgnummer: undefined, bygg: "Mustads Vei 1", kontoeier: "Susann Falkenstein", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Administrasjonssekretær" }, { name: "Kontaktperson 2" }, { name: "Kontaktperson 3" }, { name: "Kontaktperson 4" }, { name: "Kontaktperson 5" }], sisteSaker: [{ caseNumber: "00113279", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-08-11", sfUrl: null }, { caseNumber: "00113271", subject: "(sak - detaljer i lokal versjon)", status: "Closed", dato: "2026-08-11", sfUrl: null }, { caseNumber: "00113268", subject: "(sak - detaljer i lokal versjon)", status: "Ny", dato: "2026-08-11", sfUrl: null }], sfUrl: null },
  { id: "t30", kontonavn: "Demokunde 58", kundenummer: "11141", orgnummer: undefined, bygg: undefined, kontoeier: "Camilla Bang Hoff", adresse: undefined, kontakter: [{ name: "Kontaktperson 1", title: "Head of PR & Marketing" }, { name: "Kontaktperson 2", title: "Head of .." }, { name: "Kontaktperson 3", title: "Daglig leder i reklamebyrået Fortress." }, { name: "Kontaktperson 4", title: "Butikkleder" }, { name: "Kontaktperson 5", title: "Butikkansatt" }], sisteSaker: [{ caseNumber: "00112892", subject: "(sak - detaljer i lokal versjon)", status: "Closed", dato: "2026-08-04", sfUrl: null }, { caseNumber: "00112693", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-31", sfUrl: null }, { caseNumber: "00111217", subject: "(sak - detaljer i lokal versjon)", status: "Lukket", dato: "2026-07-01", sfUrl: null }], sfUrl: null },
];
